version: '3'

services:
  product-service: 
    build: ./product-service
    ports:
      - 5001:5001
    # networks:
    #   - flaskapp

  cart-service:
    build: ./cart-service
    ports:
      - 5002:5002
    depends_on:
      - product-service
    # networks:
    #   - flaskapp
    

  payment-service:
    build: ./payment-service
    ports:
      - 5003:5003
    depends_on:
      - cart-service
    # networks:
    #   - flaskapp

# networks:
#   flaskapp: {}