apiVersion : apps/v1
kind : Deployment
metadata:
  name: nginx-deployment
  namespace: argocd
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      template:
        metadata:
          labels:
            app: nginx
        spec:
          containers:
            - name: nginx-container
              image: nginx:1.21
              ports:
                - containerPort: 80
