apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      name: payment-service
    selector:
      labels:
        app: payment-service
      spec:
        containers:
        - name: payment-service
          image:
          ports:
          - containerPort: 5003
  